spring:
    application:
        name: App
    profiles:
        active: dev
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: true
    datasource:
#        jndi-name: java:comp/env/jdbc/mysql
#        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://52.193.154.247:23306/sbtry
        username: ${spring.datasource.username}
        password: ${spring.datasource.password}
        driver-class-name: com.mysql.jdbc.Driver

        initialize: true

    jpa:
#       database-platform: org.hibernate.dialect.PostgreSQL94Dialect
#        database-platform: = org.hibernate.dialect.MySQL5Dialect
#        database: POSTGRESQL
        show-sql: true
        format_sql: true
#        properties:
#            hibernate.id.new_generator_mappings: true
#            hibernate.cache.use_second_level_cache: true
#            hibernate.cache.use_query_cache: false
#            hibernate.generate_statistics: true
#            hibernate.session.events.log: false
#            hibernate.temp.use_jdbc_metadata_defaults: false            
        hibernate:
          ddl-auto: create

        
server:
    port: 8080
    

application:
#    datasource: # in addition to the standard spring.datasource properties
#        cachePrepStmts: true
#        prepStmtCacheSize: 250
#        prepStmtCacheSqlLimit: 2048
#        useServerPrepStmts: true
    security:
        jwt:
            secret: 5867a8374e7c0f6284b177b48faf89e1c79d72d8
            token-validity-in-seconds: 86400 # 24 hour
            token-validity-in-seconds-for-remember-me: 2592000